name = "gleamstar"
version = "1.0.1"
description = "The A* search algorithm implemented in gleam"
licences = ["MIT"]
repository = { type = "github", user = "dinkelspiel", repo = "gleamstar" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
